config/routes.rb
Rails.application.routes.draw do
  ##### PAGES
  root to:"pages#home"
  get "/home", to: "pages#home" , as:"principal"
  get "/casa", to: "pages#casa"
  get "/franquicias/:nombre", to: "pages#tiendas", as:"franquicias"
  #####
  ##### ENTRADAS
  resources :entradas, path_names: { new: 'nuevo'}
  get "/entradas/:id/destroy", to: "entradas#destroy", as: "entrada_destroy"
  #####
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entrada.rb
class Entrada < ApplicationRecord
    validates :titulo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entradas_controller.rb
class EntradasController < ApplicationController
    #listado de todas las entradas
    def index
        @entradas = Entrada.all
      end
    #Visualizar una entrada con Id
    def show
        @entrada=Entrada.find(params[:id])
    end
    #Presentamos el FORMULARIO PARA UN EDIT
    def edit
        @entrada = Entrada.find(params[:id])
    end
    #Presentamos el FORMULARIO PARA UN INSERT
    def new
        @entrada = Entrada.new
    end
    #Recogemos los datos PARA EL INSERT a partir del new
    def create
        @entrada= Entrada.new(entrada_params)
        if @entrada.save
            redirect_to @entrada
        else
            render "new"
        end
    end 
    #Recogemos los datos PARA EL INSERT a partir del new
    def update
        @entrada= Entrada.find(params[:id])
        @entrada.update(entrada_params)
        redirect_to @entrada
    end
    def destroy
        @entrada = Entrada.find(params[:id])
        @entrada.destroy
     
        redirect_to entradas_path
    end
    #metodos internos
    private
    def entrada_params
        params.require(:entrada).permit(:titulo, :texto)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    layout "pagesLayout"
    def home
        @nombre="Paco"
    end
    def tiendas
        @tienda=params[:nombre]
        @tiendas=["Tienda BCN","Tienda VLC"]
    end
    def casa
        redirect_to principal_url
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entrada_helper.rb
module EntradaHelper
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/entradas/_form.html.erb
<%= form_with model: @entrada, local: true do |form| %>
  <% if @entrada.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@entrada.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @entrada.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :titulo %><br>
    <%= form.text_field :titulo %>
  </p>
 
  <p>
    <%= form.label :texto %><br>
    <%= form.text_area :texto %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/entradas/create.html.erb
<h1>Datos de articulo</h1>
    <% @entrada.each do |dato| %>
    <li><%= dato%></li>
    <% end %>

app/views/entradas/edit.html.erb
<h1>Nueva Entrada</h1>


<h1>Editar Entrada</h1>
 
<%= render 'form' %>

app/views/entradas/index.html.erb
<h1>Listado Entradas</h1>
 
<table>
  <tr>
    <th>Titulo</th>
    <th>Texto</th>
    <th>Creado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @entradas.each do |entrada| %>
    <tr>
      <td><%= entrada.titulo %></td>
      <td><%= entrada.texto %></td>
      <td><%= entrada.created_at %></td>
      <td><%= link_to 'Mostrar', entrada_path(entrada) %></td>
      <td><%= link_to 'Editar', edit_entrada_path(entrada) %></td>
      <td><%= link_to 'Eliminar', entrada_destroy_path(entrada)%></td>
    </tr>
  <% end %>
</table>

app/views/entradas/new.html.erb
<h1>Nueva Entrada</h1>

<%= render 'form' %>

app/views/entradas/show.html.erb
<h1>Entrada, <%=@entrada.id%></h1>
<div>
    <p>Id:<%=@entrada.id%></p>
    <p><b>Titulo:<%=@entrada.titulo%></b></p>
    <p>Texto:<%=@entrada.texto%></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogBCN</title>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pagesLayout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pages for BCN Blog</title>
    <%= stylesheet_link_tag "estilos.css" %>
  </head>

  <body>
    <ul>
      <li><%= link_to "Link a Franquicias", franquicias_path("VLC")%></li>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class="titulo">Estoy en el home</h1>
<h2>Foto de <%=@nombre%>
<%= image_tag "logo.jpg", alt: "Logo" %>

app/views/pages/tiendas.html.erb
<h1>TIENDAS</h1>
<ul>
<% @tiendas.each do |tienda|%>
<li><%=tienda%></li>
<% end %>

<p>La tienda elegida es:<%=@tienda%></p>
</ul>